# Generated by Django 5.1.3 on 2024-11-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
