# Generated by Django 4.1 on 2024-11-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_ticket_banner_ticket_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="email_sent",
            field=models.BooleanField(default=True),
        ),
    ]
