# Generated by Django 4.1 on 2024-11-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_ticket_email_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
