# Generated by Django 4.1 on 2024-11-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_ticket_ticket_generated_alter_ticket_email_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticket_generated",
            field=models.BooleanField(default=True),
        ),
    ]
