# Generated by Django 4.1 on 2025-10-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_alter_ticket_ticket_generated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="logo",
            field=models.ImageField(
                blank=True, default="default/logo.jpg", null=True, upload_to="logos/"
            ),
        ),
    ]
