# Generated by Django 4.1 on 2025-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0008_alter_ticket_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="logo",
            field=models.ImageField(
                blank=True, default="default/logo.png", null=True, upload_to="logos/"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="payment_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
